default:
  max_tokens: max_tokens
  temperature: temperature 
  top_p: top_p 
  stop_sequences: stop_sequences 
  stream: stream

aws:
  maxTokens: max_tokens
  temperature: temperature
  topP: top_p
  stopSequences: stop_sequences

anthropic:
  max_tokens: max_tokens


